/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import React, { useState } from "react";
import { useMessaging } from "@footron/controls-client";
import {
  FormControl,
  NativeSelect,
  InputLabel,
  Checkbox,
  FormControlLabel,
  FormGroup, Slider
} from "@material-ui/core";
import { useCallback } from "react";

const containerStyle = css`
  padding: 16px;
  overflow-x: hidden;

  p {
    margin: 0 0 16px;
  }
`;

const names = [
[ 0, 'Trevor Ah Sue' ],
[ 1, 'Zachary Alger' ],
[ 2, 'Adam Allred' ],
[ 3, 'Paden Allsup' ],
[ 4, 'Rand Alrabadi' ],
[ 5, 'Alexis Alvarez' ],
[ 6, 'Jacob Amosa' ],
[ 7, 'Brigham Andersen' ],
[ 8, 'Connor Anderson' ],
[ 9, 'Corban Anderson' ],
[ 10, 'Jason Anderson' ],
[ 11, 'Thalia Archibald' ],
[ 12, 'Jacob Armenta' ],
[ 13, 'Ryan Arnesen' ],
[ 14, 'Kurumi Asano' ],
[ 15, 'Trevor Ashby' ],
[ 16, 'Jenna Atkinson' ],
[ 17, 'Jacob Ballard' ],
[ 18, 'Nolan Barry' ],
[ 19, 'McKay Barton' ],
[ 20, 'Jacob Bastian' ],
[ 21, 'Avery Bates' ],
[ 22, 'Miles Batey' ],
[ 23, 'Carson Baughan' ],
[ 24, 'Drew Bayles' ],
[ 25, 'Josh Bedwell' ],
[ 26, 'James Spencer Belnap' ],
[ 27, 'Jeanpierre Bendezu Ortega' ],
[ 28, 'Nathaniel Benham' ],
[ 29, 'Alec Bingham' ],
[ 30, 'Benjamin Bischoff' ],
[ 31, 'Madeline Bisel' ],
[ 32, 'Sam Bishop' ],
[ 33, 'Ryan Black' ],
[ 34, 'Andrew Bonnett' ],
[ 35, 'Devin Bowman' ],
[ 36, 'Sid Bradshaw' ],
[ 37, 'Sean Brady' ],
[ 38, 'Michael Bramwell' ],
[ 39, 'Spencer Brosnahan' ],
[ 40, 'Alex Brown' ],
[ 41, 'Kimberly Brown' ],
[ 42, 'Michael Brown' ],
[ 43, 'Joe Brundage' ],
[ 44, 'Harrison Burgess' ],
[ 45, 'Anne Burt' ],
[ 46, 'Forrest Burton' ],
[ 47, 'Nathan Byers' ],
[ 48, 'Jerome Campbell' ],
[ 49, 'Lucas Castro' ],
[ 50, 'Carolynn Chang' ],
[ 51, 'Kirsten Alexandra Chapman' ],
[ 52, 'Garrett Charles' ],
[ 53, 'Jungjin Cho' ],
[ 54, 'Rikki Choi' ],
[ 55, 'Adara Christensen' ],
[ 56, 'Ammon Christensen' ],
[ 57, 'Jacob Christensen' ],
[ 58, 'Cameron Churchill' ],
[ 59, 'Noah Cindrich' ],
[ 60, 'Nathan Clark' ],
[ 61, 'Spring Cullen' ],
[ 62, 'Jared Curtis' ],
[ 63, 'Megan Dahl' ],
[ 64, 'James Dansie' ],
[ 65, 'Dallin Davis' ],
[ 66, 'Ethan Davis' ],
[ 67, 'Tade Davis' ],
[ 68, 'Theo Dawson' ],
[ 69, 'Lexi Delorey' ],
[ 70, 'Jack Demke' ],
[ 71, 'Luqi Deng' ],
[ 72, 'Michael Didier' ],
[ 73, 'Teiresias Downing' ],
[ 74, 'Jake Dustin' ],
[ 75, 'Devin Eastmond' ],
[ 76, 'Nathan Edwards' ],
[ 77, 'Kyle Ellingson' ],
[ 78, 'Kye Elliott' ],
[ 79, 'Bradley English' ],
[ 80, 'Carlos Evelo' ],
[ 81, 'Spencer Fairchild' ],
[ 82, 'Brady Farley' ],
[ 83, 'Tammy Farnsworth' ],
[ 84, 'Travis Feller' ],
[ 85, 'Calvin Fischer' ],
[ 86, 'James Fitzgerald' ],
[ 87, 'Davis Forster' ],
[ 88, 'Austin Foster' ],
[ 89, 'Brandon Fowler' ],
[ 90, 'Jason Fox' ],
[ 91, 'Benjamin Frodsham' ],
[ 92, 'Todd Froisland' ],
[ 93, 'Duncan Furgeson' ],
[ 94, 'Kate Gammon' ],
[ 95, 'Siqi Gao' ],
[ 96, 'Fernando Garcia' ],
[ 97, 'Cyrus Gatrell' ],
[ 98, 'Jacob Gehrett' ],
[ 99, 'Easton Gibson' ],
[ 100, 'Nathan Gillis' ],
[ 101, 'Corbin Gollaher' ],
[ 102, 'Manuel Gordillo' ],
[ 103, 'Ben Grant' ],
[ 104, 'Rachel Grant' ],
[ 105, 'Kade Greenburg' ],
[ 106, 'Haley Greer' ],
[ 107, 'Aimee Gundersen' ],
[ 108, 'Kyle Gwilliam' ],
[ 109, 'Dallin Hagman' ],
[ 110, 'Will Hainsworth' ],
[ 111, 'Abby Hales' ],
[ 112, 'Eliza Hales' ],
[ 113, 'Justin Hales' ],
[ 114, 'Cara Hamilton' ],
[ 115, 'Conner Hammond' ],
[ 116, 'Jake Hamzawi' ],
[ 117, 'Benjamin Harden' ],
[ 118, 'Craig Harris' ],
[ 119, 'Jacob Harris' ],
[ 120, 'David Hart' ],
[ 121, 'David Hawley' ],
[ 122, 'Kirsten Hema' ],
[ 123, 'Dallin Henderson' ],
[ 124, 'Jeonghaeng Heo' ],
[ 125, 'Allyse Hettinger' ],
[ 126, 'Josh Higgins' ],
[ 127, 'Joshua Higgins' ],
[ 128, 'Jordan Higham' ],
[ 129, 'Justin Hill' ],
[ 130, 'Kevin Hillyard' ],
[ 131, 'Braeden Hintze' ],
[ 132, 'Andrew Hirschi' ],
[ 133, 'Joel Hirschmann' ],
[ 134, 'Brian Holderness' ],
[ 135, 'Chad Holmes' ],
[ 136, 'Jared Householder' ],
[ 137, 'Analeigh Howard' ],
[ 138, 'Stephen Howard' ],
[ 139, 'Jackie Hu' ],
[ 140, 'Benjamin Humphries' ],
[ 141, 'Caleb Hunt' ],
[ 142, 'Samuel Hunter' ],
[ 143, 'Wesley Ijams' ],
[ 144, 'Riley Isom' ],
[ 145, 'Kaleah Jackson' ],
[ 146, 'Brendan Jensen' ],
[ 147, 'Connor Jensen' ],
[ 148, 'Kyungwoo Jo' ],
[ 149, 'Adam Johnson' ],
[ 150, 'Eric Jorgensen' ],
[ 151, 'Hongjoon Jun' ],
[ 152, 'Tyler Karren' ],
[ 153, 'Truman Kautzman' ],
[ 154, 'Adnan Khayyat' ],
[ 155, 'Braeden Kilburn' ],
[ 156, 'Munseok Kim' ],
[ 157, 'Taeho Kim' ],
[ 158, 'YoungChan Kim' ],
[ 159, 'Briana King' ],
[ 160, 'Elli King' ],
[ 161, 'Branden Kinghorn' ],
[ 162, 'Gregory Knapp' ],
[ 163, 'Ben Knight' ],
[ 164, 'Savannah Knight' ],
[ 165, 'Divya Kusuluri' ],
[ 166, 'Jeremy Lakey' ],
[ 167, 'Stephen Lambert' ],
[ 168, 'Mark Larsen' ],
[ 169, 'Nathan Larsen' ],
[ 170, 'Dominic Lauricella' ],
[ 171, 'Drayton Lavender' ],
[ 172, 'Brandon Vinh Le' ],
[ 173, 'Maxwell Lenker' ],
[ 174, 'Thomas Leonard' ],
[ 175, 'Jeremy Lewis' ],
[ 176, 'Koby Lewis' ],
[ 177, 'Jongwoo Lim' ],
[ 178, 'Jordan Lin' ],
[ 179, 'Tyler Little' ],
[ 180, 'Ethan Low' ],
[ 181, 'Josh Mann' ],
[ 182, 'Tyler Mansell' ],
[ 183, 'Elias Maple' ],
[ 184, 'Samuel Marberger' ],
[ 185, 'Zachary Marshall' ],
[ 186, 'Brennan Martin' ],
[ 187, 'Jax Matthews' ],
[ 188, 'JC May' ],
[ 189, 'Trevor McClellan' ],
[ 190, 'Jason McDonald' ],
[ 191, 'Ethan McKague' ],
[ 192, 'Nathan McMurray' ],
[ 193, 'Jesse Melville' ],
[ 194, 'Will Melville' ],
[ 195, 'Irvin Mendoza Rojas' ],
[ 196, 'Chris Mero' ],
[ 197, 'Zack Mertz' ],
[ 198, 'Lance Meurs' ],
[ 199, 'Zack Meyer' ],
[ 200, 'Kristopher Miles' ],
[ 201, 'Ben Millett' ],
[ 202, 'Jacob Moberly' ],
[ 203, 'Cameron Molen' ],
[ 204, 'Ameilya Monson' ],
[ 205, 'Cole Monson' ],
[ 206, 'Kekoapoaono Montalbo' ],
[ 207, 'Jamison Moody' ],
[ 208, 'Jae Moon' ],
[ 209, 'Neal Munson' ],
[ 210, 'Cori Nally' ],
[ 211, 'Yeganeh Nasiri' ],
[ 212, 'Tustin Neilson' ],
[ 213, 'Jonathan Nelson' ],
[ 214, 'Stephen Nelson' ],
[ 215, 'Steven Nelson' ],
[ 216, 'Aadesh Neupane' ],
[ 217, 'Sam Nichols' ],
[ 218, 'Logan Nielsen' ],
[ 219, 'Jacob Nuttall' ],
[ 220, 'Ryan Ogden' ],
[ 221, 'Suguru Onda' ],
[ 222, 'Dylan Packham' ],
[ 223, 'Inoh Pak' ],
[ 224, 'Rembrand Pardo Castro' ],
[ 225, 'Joe Paris' ],
[ 226, 'Jaeyoung Park' ],
[ 227, 'Sihnyoung Park' ],
[ 228, 'Ethan Payne' ],
[ 229, 'Jeremy Payne' ],
[ 230, 'Zach Payne' ],
[ 231, 'Ethan Pedersen' ],
[ 232, 'Mark Pedersen' ],
[ 233, 'Connor Stephen Pemberton' ],
[ 234, 'Amadeus Peterson' ],
[ 235, 'Joseph Peterson' ],
[ 236, 'Maddie Petty' ],
[ 237, 'Britton Player' ],
[ 238, 'Ryan Poertner' ],
[ 239, 'Clay Poffenberger' ],
[ 240, 'Ammon Quackenbush' ],
[ 241, 'PJ Rape Jr' ],
[ 242, 'Josh Rathke' ],
[ 243, 'Isaac Raval' ],
[ 244, 'Gabriel Reed' ],
[ 245, 'Riley Reed' ],
[ 246, 'David Reynolds' ],
[ 247, 'Michael Richards' ],
[ 248, 'Jack Richardson' ],
[ 249, 'Joshua Richardson' ],
[ 250, 'Nathan William Riches' ],
[ 251, 'Tyler Richey' ],
[ 252, 'Kaleb Rigg' ],
[ 253, 'Jason Roberts' ],
[ 254, 'Brian Robinson' ],
[ 255, 'Tyson Rodriguez' ],
[ 256, 'Ignacio Rodriguez de Almeida' ],
[ 257, 'Adam Rollins' ],
[ 258, 'Eric Rose' ],
[ 259, 'Jared Rossberg' ],
[ 260, 'Mark Roth' ],
[ 261, 'Nate Roylance' ],
[ 262, 'Matthew Russon' ],
[ 263, 'Ken Ruth' ],
[ 264, 'Adam Ryan' ],
[ 265, 'Christopher Rytting' ],
[ 266, 'Mitchell Saatkamp' ],
[ 267, 'Noah Schill' ],
[ 268, 'Joseph Scholl' ],
[ 269, 'Heather Schone' ],
[ 270, 'Trevor Schwantes' ],
[ 271, 'Jake Searle' ],
[ 272, 'Jarod Searle' ],
[ 273, 'Kierra Searle' ],
[ 274, 'Daniel Segrera' ],
[ 275, 'Ben Shafer' ],
[ 276, 'Alex Shaw' ],
[ 277, 'Xinru Shen' ],
[ 278, 'Bryan Nishan Sheranian' ],
[ 279, 'Taylor Shiozawa' ],
[ 280, 'Ammon Shurtz' ],
[ 281, 'Michael Skonnard' ],
[ 282, 'Brenden Smith' ],
[ 283, 'Russell Smith' ],
[ 284, 'Skyler Smith' ],
[ 285, 'Teikn Smith' ],
[ 286, 'Rebekah Sowards' ],
[ 287, 'Eric Spencer' ],
[ 288, 'Brad Spendlove' ],
[ 289, 'Ella Catherine Spigarelli' ],
[ 290, 'Thomas Stansel' ],
[ 291, 'Andy Staples' ],
[ 292, 'Dakota Stevens' ],
[ 293, 'Kyle Storey' ],
[ 294, 'Casey Strong' ],
[ 295, 'Jared Strong' ],
[ 296, 'John Swingle' ],
[ 297, 'Daniel Taylor' ],
[ 298, 'Hayden Taylor' ],
[ 299, 'Jacob Taylor' ],
[ 300, 'Bethaly Tenango Anaya' ],
[ 301, 'Michael Teuscher' ],
[ 302, 'Stewart Thompson' ],
[ 303, 'JJ Thorley' ],
[ 304, 'Alexa Urrea' ],
[ 305, 'Victor Velasco' ],
[ 306, 'Payton Viloria' ],
[ 307, 'Ethan Taylor Walch' ],
[ 308, 'Acacia Warner' ],
[ 309, 'Adam Warnick' ],
[ 310, 'Ammon Warnick' ],
[ 311, 'Caleb Washburn' ],
[ 312, 'Jasmine Webb' ],
[ 313, 'Kai Weight' ],
[ 314, 'Danny Wensel' ],
[ 315, 'Paul Wertenbaker' ],
[ 316, 'Chris West' ],
[ 317, 'Chase Westhoff' ],
[ 318, 'Reagan Weston' ],
[ 319, 'Angel Wheelwright' ],
[ 320, 'Brigham Whitaker' ],
[ 321, 'Haley Wiese' ],
[ 322, 'Josh Willis' ],
[ 323, 'Josh Wilson' ],
[ 324, 'Lexie Wilsted' ],
[ 325, 'Grant Windsor' ],
[ 326, 'Jinxin Yu' ],
[ 327, 'Xin Zhao' ],
]

const ControlsComponent = (): JSX.Element => {
  const [name, setName] = useState<string>("");

  const { sendMessage } = useMessaging<any>();

  const handleNameChange = (event: React.ChangeEvent<{ name?: string; value: string }>) => {
    const name = event.target.value;
    setName(name);
    sendMessage(name)
  };

  return (
    <div css={containerStyle}>
      <FormGroup>
        <p>
          <b>Pick your name from the list to see it on the big screen! (Your name will show for 60 seconds)</b>
        </p>
        <FormControl>
          <InputLabel htmlFor="name-native-helper">Name</InputLabel>
          <NativeSelect
            inputProps={{
              name: 'Name',
              id: 'name-native-helper',
            }}
            id="demo-simple-select"
            value={name}
            name="Name"
            onChange={handleNameChange}
          >
            <option value="all">All names</option>
            {
              names.map((name) => <option key={"id"} value={name[0]}>{name[1]}</option>)
            }
          </NativeSelect>
        </FormControl>
      </FormGroup>
    </div>
  );
};

export default ControlsComponent;
