/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import React, { useState } from "react";
import { useMessaging } from "@footron/controls-client";
import {
  FormControl,
  NativeSelect,
  InputLabel,
  Checkbox,
  FormControlLabel,
  FormGroup, Slider
} from "@material-ui/core";
import { useCallback } from "react";

const containerStyle = css`
  padding: 16px;
  overflow-x: hidden;

  p {
    margin: 0 0 16px;
  }
`;

const names = [
[ 0, 'Dallan Hales Adamson' ],
[ 1, 'Luke Albin' ],
[ 2, 'Rylee May Albrecht' ],
[ 3, 'Dylan Barratt Allen' ],
[ 4, 'Sydney Allen Nielson' ],
[ 5, 'Kelly Camille Alvarado Plasencia' ],
[ 6, 'Arotoa Haetaautiatinu Anderson' ],
[ 7, 'Connor Stanley Anderson' ],
[ 8, 'Trevor Nielson Andrus' ],
[ 9, 'Stanton Tannous Yow-Seng Anthony' ],
[ 10, 'Kaylee Jo Anthony' ],
[ 11, 'Jacob Gallardo Armenta' ],
[ 12, 'Adam True Arnett' ],
[ 13, 'Jeffrey Allen Arnold' ],
[ 14, 'Emily Rose Asplund' ],
[ 15, 'Noor Shawkat Assi' ],
[ 16, 'Emma Katherine Ausman' ],
[ 17, 'Seungyeol Baek' ],
[ 18, 'James Elias Baker' ],
[ 19, 'Jared Loren Barker' ],
[ 20, 'Dallin Bradley Bartholomew' ],
[ 21, 'Lucy Marie Barton' ],
[ 22, 'Zachary James Roger Beach' ],
[ 23, 'Samuel Matthias Bennion' ],
[ 24, 'Samuel David Bennion' ],
[ 25, 'Brennan Tag Bertola' ],
[ 26, 'Vigynesh Bhatt' ],
[ 27, 'Jared Hyrum Black' ],
[ 28, 'Andrew Joseph Blackman' ],
[ 29, 'Daniel Scott Blanchard' ],
[ 30, 'Gavin M Bolin' ],
[ 31, 'Ethan M Borsky' ],
[ 32, 'McKay Thomas Bowcut' ],
[ 33, 'Dallin Gary Bowie' ],
[ 34, 'Jacob Daniel Bowman' ],
[ 35, 'Omar Emmanuel Briceno-Nunez' ],
[ 36, 'Brian Charles Brown' ],
[ 37, 'Taylor Mark Brown' ],
[ 38, 'Derrick Lee Brundage' ],
[ 39, 'Alec Kent Burnett' ],
[ 40, 'Sarah Genieve Buss' ],
[ 41, 'Courtni Linae Byun' ],
[ 42, 'Kylie Joana Major Callaway' ],
[ 43, 'Darien Alexander Campbell' ],
[ 44, 'Xuan Cao' ],
[ 45, 'Samuel Gregory Carlsen' ],
[ 46, 'Moisés AbinadÃ­ Carpio Lazo' ],
[ 47, 'Sarah Jean Kharaka Carson' ],
[ 48, 'Clayton Christian Chase' ],
[ 49, 'Spencer Jorden Chavez' ],
[ 50, 'Jonathan Reeve Chelius' ],
[ 51, 'Kai Chen' ],
[ 52, 'Brian Jun Xian Chi' ],
[ 53, 'Jordan Alan Chwalik' ],
[ 54, 'Cameron Ray Clark' ],
[ 55, 'Austin Paul Clarke' ],
[ 56, 'Aaron Michael Clayton' ],
[ 57, 'Kendall Matthew Clement' ],
[ 58, 'Tanner Reid Clements' ],
[ 59, 'Benjamin Tait Cookson' ],
[ 60, 'Minhoru Jushara Cotache Leon' ],
[ 61, 'Stephen Holmes Cowley' ],
[ 62, 'Bridger Reese Danby' ],
[ 63, 'Tanner Brokaw Day' ],
[ 64, 'Tyler Ross Dean' ],
[ 65, 'Hannah Isabell Decker' ],
[ 66, 'Walter DeGering' ],
[ 67, 'Stephen Aaron Derbidge' ],
[ 68, 'Bryan Jay Despain' ],
[ 69, 'Paige Irene Despain' ],
[ 70, 'Jared Evans Devenport' ],
[ 71, 'Brendan Joel Dewberry' ],
[ 72, 'Hoan Do' ],
[ 73, 'Brody Kurt Dobson' ],
[ 74, 'Jacob Heath Drake' ],
[ 75, 'Tyler Cole Draper' ],
[ 76, 'Joshua David Draper' ],
[ 77, 'Russell Joseph Dupaix' ],
[ 78, 'James Matthew Edwards' ],
[ 79, 'Joshua Jensen Egbert' ],
[ 80, 'Patrick Lloyd Elzinga' ],
[ 81, 'Marcos Espino-Moreno' ],
[ 82, 'Miguel de Nazare do Espirito Santo' ],
[ 83, 'Joshua Justin Esplin' ],
[ 84, 'Nathan Earl Fastabend' ],
[ 85, 'MacKenzie Kay Fisher' ],
[ 86, 'Benjamin Daniel Foutz' ],
[ 87, 'Jacob Lynn Frandsen' ],
[ 88, 'Seth Dalen Fredrickson' ],
[ 89, 'Quincey Martin Frewin' ],
[ 90, 'Rachel Fullerton' ],
[ 91, 'Jacob Millett Gardiner' ],
[ 92, 'Kimball Wayne George' ],
[ 93, 'Benjamin Spencer Giles' ],
[ 94, 'Jose Humberto Giraldez Chavez' ],
[ 95, 'Devon Layne Gneiting' ],
[ 96, 'Milvia Goulding' ],
[ 97, 'Matthew John Gunson Jr.' ],
[ 98, 'Francis Imad Habash' ],
[ 99, 'Zachary Mark Hacking' ],
[ 100, 'Dallin Michael Hagman' ],
[ 101, 'Christian James Hall' ],
[ 102, 'Payton James Hall' ],
[ 103, 'Maxwell Alldredge Hamilton' ],
[ 104, 'Hunter Regan Hansen' ],
[ 105, 'Nathaniel Lee Hanson' ],
[ 106, 'Caleb Marshall Harding' ],
[ 107, 'Cal Hargis' ],
[ 108, 'Micah Moroni Harps' ],
[ 109, 'Emma Christine Harrington' ],
[ 110, 'Austin Lee Harris' ],
[ 111, 'Jacob Paul Hart' ],
[ 112, 'Andrew James Hartsfield' ],
[ 113, 'Jackson LeRoy Harwood' ],
[ 114, 'Bradley Dean Hatch' ],
[ 115, 'Paul Carlos Hathaway' ],
[ 116, 'Michael James Hawks' ],
[ 117, 'Joshua David Hemmert' ],
[ 118, 'David Hernandez Martinez' ],
[ 119, 'Michael William Holland' ],
[ 120, 'Stephen R Hood' ],
[ 121, 'Alexis Lynn Hovorka' ],
[ 122, 'Zhengyang Huang' ],
[ 123, 'Pearl Kathleen Hulbert' ],
[ 124, 'Dallin Cole Hunter' ],
[ 125, 'Sofia Grace Iannicelli' ],
[ 126, 'Ian Brent Jackson' ],
[ 127, 'Benjamin Scott Jacobs' ],
[ 128, 'Gideon Glade Jardine' ],
[ 129, 'Blake J Jensen' ],
[ 130, 'Phineas Teschner Jensen' ],
[ 131, 'Timothy Rex Jensen' ],
[ 132, 'Cody Daniel Johns' ],
[ 133, 'Joseph Smith Johnson' ],
[ 134, 'Spencer Cannon Jorgensen' ],
[ 135, 'Chetan Joshi' ],
[ 136, 'Nathaniel Dart Judd' ],
[ 137, 'Thummim Jung' ],
[ 138, 'Chahyun Kang' ],
[ 139, 'Hanbich Kang' ],
[ 140, 'Gabriella Chretienne Kang' ],
[ 141, 'Tyler Carl Karren' ],
[ 142, 'Chance Hunter Kearl' ],
[ 143, 'Mahmoud Ibrahim Khalil' ],
[ 144, 'Taeyang Kim' ],
[ 145, 'Kevin Mathew Kinney' ],
[ 146, 'Logan Dennis Kitchen' ],
[ 147, 'Kaden Andrew Klein' ],
[ 148, 'Carson Kurt Koehle' ],
[ 149, 'Spencer Isaac Kraus' ],
[ 150, 'James Allan Krueger' ],
[ 151, 'Daria Mykolaivna Kukharuk' ],
[ 152, 'Jacob Graham Kullberg' ],
[ 153, 'Nathaniel Lampros' ],
[ 154, 'Justin Dean Lapicola' ],
[ 155, 'Derek Milton Larsen' ],
[ 156, 'Elizabeth Ann Larsen' ],
[ 157, 'Hunter Robert Larson' ],
[ 158, 'Kymberly Larson' ],
[ 159, 'Sean Arden Last' ],
[ 160, 'Elliot Jack Layton' ],
[ 161, 'Chin Hei Helaman Lee' ],
[ 162, 'Joshua Thomas Lee' ],
[ 163, 'Ryan Douglas Lee' ],
[ 164, 'Leo Taylor LeSueur' ],
[ 165, 'Grant Spencer Lewis' ],
[ 166, 'Zarin Platz Loosli' ],
[ 167, 'Jaden Quinn Lorenc' ],
[ 168, 'Christian Chantabury Luangrath' ],
[ 169, 'Colby John Lyman' ],
[ 170, 'Malcolm Grant MacGregor' ],
[ 171, 'Jordan PÅhaku  Mack' ],
[ 172, 'Michael Hunter Madsen' ],
[ 173, 'Blake Andrew Martin' ],
[ 174, 'Phillip Mark Mason' ],
[ 175, 'Max Doyle Mason' ],
[ 176, 'Andres Eduardo Matos' ],
[ 177, 'Gabriel Taylor Maxfield' ],
[ 178, 'Thomas James Maxwell' ],
[ 179, 'Bright Mazura' ],
[ 180, 'Justin Andrew McBride' ],
[ 181, 'Rose Clarice Filichia McClure' ],
[ 182, 'Tyson John McCulloch' ],
[ 183, 'Emily Eliza McDermott' ],
[ 184, 'Jason Michael McDonald' ],
[ 185, 'Isaac Hatch McGill' ],
[ 186, 'Nathan Charles McGrew' ],
[ 187, 'Jacob Scott McKenzie' ],
[ 188, 'Ryan Michael Meyer' ],
[ 189, 'Ethan Lee Michaelis' ],
[ 190, 'Caelen Dale Miller' ],
[ 191, 'Daniel Frank Millward' ],
[ 192, 'Spencer Gordon Moffat' ],
[ 193, 'Andres Felipe Molina Ospina' ],
[ 194, 'Jared Mark Montierth' ],
[ 195, 'Gage Bentley Moore' ],
[ 196, 'Victoria On-Kei Moreno' ],
[ 197, 'Jacob Gordon Morrey' ],
[ 198, 'Melissa Amber Morris' ],
[ 199, 'Andrew Clendon Moss' ],
[ 200, 'Jeremy Russell Mumford' ],
[ 201, 'Hannah Kristine Nelson' ],
[ 202, 'Abel Ware Nelson' ],
[ 203, 'Peter Hinckley Neubert' ],
[ 204, 'Alexander Charles Neville' ],
[ 205, 'Jonas Christian Nielsen' ],
[ 206, 'Michael Brian Norris' ],
[ 207, 'Samuel Anders Olausson' ],
[ 208, 'Justin Paul Olcott' ],
[ 209, 'Suguru Onda' ],
[ 210, 'Dillon Jeremy Ormond' ],
[ 211, 'Nathan Rhead Owen' ],
[ 212, 'Christopher Braxton Owens' ],
[ 213, 'Andrew Robert Palmer' ],
[ 214, 'Jooyeon Park' ],
[ 215, 'Patrick Jefferson Parker' ],
[ 216, 'Elizabeth Grace Parkinson' ],
[ 217, 'David Matthew Parrott' ],
[ 218, 'Eden Khan Paupulaire' ],
[ 219, 'Matthew Benjamin Peart' ],
[ 220, 'Sara Marie Peel' ],
[ 221, 'Rachel Marie Perrier' ],
[ 222, 'Gabriel Michael Perry' ],
[ 223, 'Hana Pertab' ],
[ 224, 'Andrew Birch Peterson' ],
[ 225, 'Joseph Alexander Stuart Peterson' ],
[ 226, 'Isaac William Peterson' ],
[ 227, 'Jackson Lee Peterson' ],
[ 228, 'Bryce McKay Pierson' ],
[ 229, 'Justin Warren Ponton' ],
[ 230, 'Timothy James Pope' ],
[ 231, 'William Teague Porter' ],
[ 232, 'Joseph Nathaniel Poulson' ],
[ 233, 'Matthew Edward Powley' ],
[ 234, 'Noah Jacob Pratt' ],
[ 235, 'McKayla Noelle Pressler' ],
[ 236, 'Garrett Lynn Price' ],
[ 237, 'Calvin Benjamin Pugmire' ],
[ 238, 'Alex Qian' ],
[ 239, 'Delaney Margaret Reed' ],
[ 240, 'Jared Ryan Renberg' ],
[ 241, 'Kathryn Dee Rencher' ],
[ 242, 'Nathan Charles Rice' ],
[ 243, 'Charles Coulson Rich' ],
[ 244, 'Michael Lynn Richards' ],
[ 245, 'Jacob Richmond' ],
[ 246, 'Benjamin David Ricks' ],
[ 247, 'Beckett Kimber Ricks' ],
[ 248, 'Kyle Jeffrey Rogers' ],
[ 249, 'Riley Grant Ross' ],
[ 250, 'Adam Jared Rounsville' ],
[ 251, 'Jaxson Waters Ruff' ],
[ 252, 'Cole Brian Russon' ],
[ 253, 'Garrett Neil Sapp' ],
[ 254, 'Nicole Sue Sapp' ],
[ 255, 'Vijay Kiran Satyam' ],
[ 256, 'Anson Raymond Savage' ],
[ 257, 'Jakob Neal Schilling' ],
[ 258, 'Benjamin Isaac Schulzke' ],
[ 259, 'Melissa Leigh Scott' ],
[ 260, 'Samuel Todd Seager' ],
[ 261, 'Jackson Jay Searle' ],
[ 262, 'Peter Andrew Seely' ],
[ 263, 'Benjamin Jeffrey Shafer' ],
[ 264, 'Brady James Sillito' ],
[ 265, 'Elliot Alexandre Silveira' ],
[ 266, 'Ethan Holland Simmons' ],
[ 267, 'Riley Jacob Sinema' ],
[ 268, 'Scott David Slinn' ],
[ 269, 'Brennan Jacob Smeltzer' ],
[ 270, 'Mark John Smiley' ],
[ 271, 'Jason Paul Smith' ],
[ 272, 'Juliana Celeste Smith' ],
[ 273, 'Kaleb Jarom Smith' ],
[ 274, 'Maxwell Steven Smith' ],
[ 275, 'Hyrum Gary Sorensen' ],
[ 276, 'Ty Scott Sorensen' ],
[ 277, 'Lawry Eliot Sorenson' ],
[ 278, 'Brody Jones Spencer' ],
[ 279, 'Abigail Joy Spigarelli' ],
[ 280, 'Gavin McCrae Steck' ],
[ 281, 'Isabella Dupré Cadena Stephens' ],
[ 282, 'Josiah Jaron Stephens' ],
[ 283, 'Michal Anne Gibson' ],
[ 284, 'John Michael Stout' ],
[ 285, 'Ren Strauss' ],
[ 286, 'Kenton Carl Strong' ],
[ 287, 'John Casey Strong' ],
[ 288, 'Tanner Jack Sundwall' ],
[ 289, 'Ashtyn Maria Taylor' ],
[ 290, 'Benjamin Ray Taylor' ],
[ 291, 'Camren Michael Taylor' ],
[ 292, 'Joshua Brubaker Taylor' ],
[ 293, 'Nicholas Dean Taylor' ],
[ 294, 'Emily Ting Teng' ],
[ 295, 'Marc Adam Terry' ],
[ 296, 'Jacob Alexander Thomsen' ],
[ 297, 'Alison Anne Rampton' ],
[ 298, 'Logan Blake Thurman' ],
[ 299, 'Josh Caleb Andrew Tidwell' ],
[ 300, 'Damon Wesley Tingey' ],
[ 301, 'Benjamin Porter Tolley' ],
[ 302, 'Gideon Matthew Tonkinson' ],
[ 303, 'Jonathan Brett Tullis' ],
[ 304, 'Nikelle Charity Turner' ],
[ 305, 'Stephen Dean Tveten' ],
[ 306, 'Zachary Ethan Tyler' ],
[ 307, 'Ernesto Antonio Valencia Arevalo' ],
[ 308, 'Troy Chandler Van Meter' ],
[ 309, 'Talden J. VanderLouw' ],
[ 310, 'Dallin Jacob Vetter' ],
[ 311, 'Conner Joseph Vigil' ],
[ 312, 'Ethan Taylor Walch' ],
[ 313, 'Cassidy Marie Waldrip' ],
[ 314, 'Nathan Douglas Walker' ],
[ 315, 'Zachary Tyler Wallace' ],
[ 316, 'Yiqi Wang' ],
[ 317, 'Austin Rex Warnick' ],
[ 318, 'Chase Martin Westhoff' ],
[ 319, 'Jack David Wheatley' ],
[ 320, 'Brianna Elaine White' ],
[ 321, 'Connor Hansen Widtfeldt' ],
[ 322, 'Quincy Gayle Wilcox' ],
[ 323, 'Connor Randall Wilhelm' ],
[ 324, 'Bryton S. Wilson' ],
[ 325, 'Andrew Martin Wilson' ],
[ 326, 'Jared D Wilson' ],
[ 327, 'Lexie Elizabeth Wilsted' ],
[ 328, 'Andrew K Winsborrow' ],
[ 329, 'Harrison Q Winslow' ],
[ 330, 'Riley Amanda Woolf' ],
[ 331, 'Eian Tred Wright' ],
[ 332, 'Tarun Kumar Yadav' ],
[ 333, 'Zachary Douglas Yancey' ],
[ 334, 'Henry Mathewson Young' ],
[ 335, 'Jinxin Yu' ],
[ 336, 'Jingyu Zhao' ],
[ 337, 'Zhuokang Zhao' ],
[ 338, 'Jacob Powell Zinn' ],
[ 339, 'Benjamin Nathan Zobrist' ],
]

const ControlsComponent = (): JSX.Element => {
  const [name, setName] = useState<string>("");

  const { sendMessage } = useMessaging<any>();

  const handleNameChange = (event: React.ChangeEvent<{ name?: string; value: string }>) => {
    const name = event.target.value;
    setName(name);
    sendMessage(name)
  };

  return (
    <div css={containerStyle}>
      <FormGroup>
        <p>
          <b>Pick your name from the list to see it on the big screen! (Your name will show for 60 seconds)</b>
        </p>
        <FormControl>
          <InputLabel htmlFor="name-native-helper">Name</InputLabel>
          <NativeSelect
            inputProps={{
              name: 'Name',
              id: 'name-native-helper',
            }}
            id="demo-simple-select"
            value={name}
            name="Name"
            onChange={handleNameChange}
          >
            <option value="all">All names</option>
            {
              names.map((name) => <option key={"id"} value={name[0]}>{name[1]}</option>)
            }
          </NativeSelect>
        </FormControl>
      </FormGroup>
    </div>
  );
};

export default ControlsComponent;
